### ISSUE TITLE
Error while ordering campaign list by segments

### ISSUE THREAD

**Issue by obrunodelgado** [remp2020/remp#32]
**Description**
When I try to order the Campaign Lists by segments, I receive this error:

![image](https://user-images.githubusercontent.com/2372140/66936959-7e565c80-f036-11e9-908b-b185c3df2a83.png)

**Steps to Reproduce**
1.  Access http://campaign.remp.press/campaigns;
2.  Order Campaign List by Segments;
3.  The error will occur;

**Facts**
During debug, we found that this errors occurs when `CollectionDataTable.php` calls `$this->ordering();` at line 158.

![image](https://user-images.githubusercontent.com/2372140/66937095-c1183480-f036-11e9-9323-5bcaccd4fd7e.png)

**Stack Trace**
```
[2019-10-16 16:05:00] production.ERROR: Undefined index: segments {"userId":6,"email":"danillo.celino@gmail.com","exception":"[object] (Yajra\\DataTables\\Exceptions\\Exception(code: 0): Undefined index: segments at /var/www/remp/Campaign/vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php:778, ErrorException(code: 0): Undefined index: segments at /var/www/remp/Campaign/vendor/yajra/laravel-datatables-oracle/src/CollectionDataTable.php:288)
[stacktrace]
#0 /var/www/remp/Campaign/vendor/yajra/laravel-datatables-oracle/src/CollectionDataTable.php(167): Yajra\\DataTables\\DataTableAbstract->errorResponse(Object(ErrorException))
#1 /var/www/remp/Campaign/app/Http/Controllers/CampaignController.php(131): Yajra\\DataTables\\CollectionDataTable->make(true)
#2 [internal function]: App\\Http\\Controllers\\CampaignController->json(Object(Yajra\\DataTables\\DataTables), Object(App\\Contracts\\SegmentAggregator))
#3 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('json', Array)
#5 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\CampaignController), 'json')
#6 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#7 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#8 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#9 /var/www/remp/Campaign/vendor/remp/laravel-sso/src/Http/Middleware/VerifyJwtToken.php(74): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#10 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Remp\\LaravelSso\\Http\\Middleware\\VerifyJwtToken->handle(Object(App\\Http\\Request), Object(Closure))
#11 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#12 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#13 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(App\\Http\\Request), Object(Closure))
#14 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#15 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#16 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(App\\Http\\Request), Object(Closure))
#17 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#18 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#19 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(App\\Http\\Request), Object(Closure))
#20 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#21 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#22 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(App\\Http\\Request), Object(Closure))
#23 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#24 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#25 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(App\\Http\\Request), Object(Closure))
#26 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#27 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#28 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(App\\Http\\Request), Object(Closure))
#29 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#30 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#31 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Request))
#33 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(App\\Http\\Request), Object(Illuminate\\Routing\\Route))
#34 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(App\\Http\\Request))
#35 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(App\\Http\\Request))
#36 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(App\\Http\\Request))
#37 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#38 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(App\\Http\\Request), Object(Closure))
#39 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#40 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#41 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(App\\Http\\Request), Object(Closure))
#42 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#43 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#44 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(App\\Http\\Request), Object(Closure))
#45 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#46 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#47 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(App\\Http\\Request), Object(Closure))
#48 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#49 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#50 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(App\\Http\\Request), Object(Closure))
#51 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Http\\Request))
#52 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(App\\Http\\Request))
#53 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /var/www/remp/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(App\\Http\\Request))
#55 /var/www/remp/Campaign/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(App\\Http\\Request))
#56 {main}
"}
```

**Comment by rootpd** [comment]
Now when I think about it, does it even make sense to have _segments_ column sortable when there can be one than one segment? What should be the rule that sorts the results? 

I can think of:

* _number of segments_ or
* _name of the first segment_.

But none of them are reasonable enough to justify. Let me know if you have something specific in mind, otherwise we'd probably disable sorting for this column.
