### ISSUE TITLE
Sql error on Mailer DB migrate

### ISSUE THREAD

**Issue by j-norwood-young** [remp2020/remp#6]
I'm installing on top of MariaDB. I'm getting the following error when running `php bin/command.php migrate:migrate` on Mailer:

```
using migration paths
 - /var/www/workspace/remp/Mailer/migrations
warning no environment specified, defaulting to: local
using adapter mysql
using database mailer

 == 20181106082909 AddExtrasToMailTemplates: migrating
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON NULL' at line 1 in /var/www/workspace/remp/Mailer/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:338
Stack trace:
#0 /var/www/workspace/remp/Mailer/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(338): PDO->exec('ALTER TABLE `ma...')
#1 /var/www/workspace/remp/Mailer/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(422): Phinx\Db\Adapter\PdoAdapter->execute('ALTER TABLE `ma...')
#2 /var/www/workspace/remp/Mailer/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(628): Phinx\Db\Adapter\MysqlAdapter->addColumn(Object(Phinx\Db\Table), Object(Phinx\Db\Table\Column))
#3 /var/www/workspace/remp/Mailer/migrations/20181106082909_add_extras_to_mail_templates.php(11): Phinx\Db\Table->update()
#4 /var/www/workspace/remp/Mailer/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(122): AddExtrasToMailTemplates->change()
#5 /var/www/workspace/remp/Mailer/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(366): Phinx\Migration\Manager\Environment->executeMigration(Object(AddExtrasToMailTemplates), 'up')
#6 /var/www/workspace/remp/Mailer/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(342): Phinx\Migration\Manager->executeMigration('local', Object(AddExtrasToMailTemplates), 'up')
#7 /var/www/workspace/remp/Mailer/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(113): Phinx\Migration\Manager->migrate('local', 20190213082954)
#8 /var/www/workspace/remp/Mailer/vendor/symfony/console/Command/Command.php(255): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/workspace/remp/Mailer/vendor/symfony/console/Application.php(953): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/workspace/remp/Mailer/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/workspace/remp/Mailer/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/workspace/remp/Mailer/bin/command.php(33): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}
```

**Comment by rootpd** [comment]
Hi, based on the error message, it looks like you're using MariaDB. What version do you have? Does it support JSON data type?

**Comment by j-norwood-young** [comment]
It's version 10.1.38-MariaDB-0ubuntu0.18.04.1. It doesn't look like MariaDB has the JSON datatype - it uses LONGTEXT instead. 

I have fixed the issue with the following migrations/20181106082909_add_extras_to_mail_templates.php:
```
<?php

use Phinx\Migration\AbstractMigration;
use Phinx\Db\Adapter\MysqlAdapter;

class AddExtrasToMailTemplates extends AbstractMigration
{
    public function change()
    {
        $this->table('mail_templates')
            ->addColumn('extras', 'text', ['null' => true, 'limit' => MysqlAdapter::TEXT_LONG])
            ->update();
    }
}
```

**Comment by rootpd** [comment]
This unfortunately wouldn't create `json` type in MySQL/Percona. Also we use JSON types in other parts of REMP tools.

Any chance you could upgrade to 10.2.7+? That version has added alias for JSON type doing exactly what you achieved by changing the migration.

https://mariadb.com/kb/en/library/json-data-type/

**Comment by j-norwood-young** [comment]
Upgrading to 10.3 has solved the problem. (I also got a "Specified key was too long" error with the previous version.)

**Comment by rootpd** [comment]
Great, we'll update the README to mention this as MariaDB might be used by more people.
